/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ApiPublicKgReindexRouteImport } from './routes/api/public/kg-reindex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKgReindexRoute = ApiPublicKgReindexRouteImport.update({
  id: '/api/public/kg-reindex',
  path: '/api/public/kg-reindex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/screening': typeof ScreeningRoute
  '/system': typeof SystemRoute
  '/api/public/kg-reindex': typeof ApiPublicKgReindexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/screening': typeof ScreeningRoute
  '/system': typeof SystemRoute
  '/api/public/kg-reindex': typeof ApiPublicKgReindexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/screening': typeof ScreeningRoute
  '/system': typeof SystemRoute
  '/api/public/kg-reindex': typeof ApiPublicKgReindexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/graph' | '/screening' | '/system' | '/api/public/kg-reindex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graph' | '/screening' | '/system' | '/api/public/kg-reindex'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/screening'
    | '/system'
    | '/api/public/kg-reindex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  ScreeningRoute: typeof ScreeningRoute
  SystemRoute: typeof SystemRoute
  ApiPublicKgReindexRoute: typeof ApiPublicKgReindexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kg-reindex': {
      id: '/api/public/kg-reindex'
      path: '/api/public/kg-reindex'
      fullPath: '/api/public/kg-reindex'
      preLoaderRoute: typeof ApiPublicKgReindexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  ScreeningRoute: ScreeningRoute,
  SystemRoute: SystemRoute,
  ApiPublicKgReindexRoute: ApiPublicKgReindexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
